#!/bin/bash
source $OPENSHIFT_CARTRIDGE_SDK_BASH
# The logic to stop your application should be put in this script.
#it survived, try to kill java
if [[ -n `ps -A | grep java` ]]; then
	pkill -SIGTERM java
fi

kill `ps -ef | grep hadoop| grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1

exit 0